/*
use master
go
*/

use SocialNetworkAlbina
go

/*
delete from PictureTags
update [User] set ProfilePictureID=null
delete from PostLikes
delete from Pictures
delete from Album
delete from Post
DBCC CHECKIDENT ('Post', RESEED, 0)
delete from MessageReceivers
delete from [Message]
DBCC CHECKIDENT ('[Message]', RESEED, 0)
delete from GroupMembers
delete from [Group]
DBCC CHECKIDENT ('[Group]', RESEED, 0)
delete from Friendship
delete from [User]
DBCC CHECKIDENT ('[User]', RESEED, 0)
delete from RelationshipStatus
DBCC CHECKIDENT ('RelationshipStatus', RESEED, 0)
delete from Hometown
DBCC CHECKIDENT ('Hometown', RESEED, 0)
*/


-- insert list of cities
insert into Hometown(City) values ('Tel Aviv')
insert into Hometown(City) values ('Moskow')
insert into Hometown(City) values ('Amsterdam')
insert into Hometown(City) values ('Jerusalem')
insert into Hometown(City) values ('Kiev')
insert into Hometown(City) values ('London')
insert into Hometown(City) values ('Ottawa')
insert into Hometown(City) values ('Stockholm')
insert into Hometown(City) values ('Tokyo')
insert into Hometown(City) values ('New York')
/*
select *
from Hometown
*/

-- insert list of relationship-status
insert into RelationshipStatus([Status]) values ('Single')
insert into RelationshipStatus([Status]) values ('Have a boyfriend')
insert into RelationshipStatus([Status]) values ('Have a girlfriend')
insert into RelationshipStatus([Status]) values ('In partnership')
insert into RelationshipStatus([Status]) values ('Married')
insert into RelationshipStatus([Status]) values ('Divorced')
/*
select *
from RelationshipStatus
*/

-- insert users
insert into [User]([UserFirstName],[UserLastName],[Email]) values ('Vasya','Pupkin','vasyap@gmail.com')
insert into [User]([UserFirstName],[UserLastName],[Email],[Workplace]) values ('Ivan','Ivanov','vanya@gmail.com','Roga&Kopyta')
insert into [User]([UserFirstName],[UserLastName],[Email], [HometownID]) values ('John','Dou','johny@gmail.com', 3)
insert into [User]([UserFirstName],[UserLastName],[Email], [RelationshipStatusID]) values ('Anne','Kogan','annek@gmail.com',5)
insert into [User]([UserFirstName],[UserLastName],[Email], [RelationshipStatusID]) values ('Yosi','Kogan','yosik@gmail.com',5)
insert into [User]([UserFirstName],[UserLastName],[Email],[TelephoneNumber]) values ('Fedya','Sidorov','feds@gmail.com','0540000000')
insert into [User]([UserFirstName],[UserLastName],[Email],[BirthDate]) values ('Albina','Gromov','grm.bina@gmail.com','1987-06-14')
insert into [User]([UserFirstName],[UserLastName],[Email]) values ('Mickey','Mouse','m@gmail.com')
insert into [User]([UserFirstName],[UserLastName],[Email]) values ('James','Bond','007@gmail.com')
insert into [User]([UserFirstName],[UserLastName],[Email]) values ('Karl','Marks','capital@gmail.com')
-- update relationships
update [User] set [InReletionshipWithID]=5 where [UserID]=4
update [User] set [InReletionshipWithID]=4 where [UserID]=5
/*
select u.UserID, u.UserID, u.UserFirstName+' '+u.UserLastName as UserFullName, h.City as Hometown,
	   u.Email, u.BirthDate, u.Workplace, u.TelephoneNumber, r.[Status], u.InReletionshipWithID,
	   ur.UserFirstName+' '+ur.UserLastName as InReletionshipWith
from [User] u left join Hometown h on u.HometownID=h.CityID
			  left join RelationshipStatus r on u.RelationshipStatusID=r.StatusID
			  left join [User] ur on u.InReletionshipWithID=ur.UserID 
*/

-- insert friendship
insert into Friendship values (1,2,1)
insert into Friendship values (2,1,1)
insert into Friendship values (1,5,1)
insert into Friendship values (5,1,1)
insert into Friendship values (1,7,1)
insert into Friendship values (7,1,1)
insert into Friendship values (1,8,1)
insert into Friendship values (8,1,1)
insert into Friendship values (1,9,1)
insert into Friendship values (9,1,1)
insert into Friendship values (2,10,1)
insert into Friendship values (10,2,1)
insert into Friendship values (2,3,1)
insert into Friendship values (3,2,1)
insert into Friendship values (2,4,1)
insert into Friendship values (4,2,1)
insert into Friendship values (2,5,1)
insert into Friendship values (5,2,1)
insert into Friendship values (2,7,1)
insert into Friendship values (7,2,1)
insert into Friendship values (2,8,1)
insert into Friendship values (8,2,1)
insert into Friendship values (3,5,1)
insert into Friendship values (5,3,1)
insert into Friendship values (3,8,1)
insert into Friendship values (8,3,1)
insert into Friendship values (3,9,1)
insert into Friendship values (9,3,1)
insert into Friendship values (3,10,1)
insert into Friendship values (10,3,1)
insert into Friendship values (4,5,1)
insert into Friendship values (5,4,1)
insert into Friendship values (4,6,1)
insert into Friendship values (6,4,1)
insert into Friendship values (4,8,1)
insert into Friendship values (8,4,1)
insert into Friendship values (4,9,1)
insert into Friendship values (9,4,1)
insert into Friendship values (4,10,1)
insert into Friendship values (10,4,1)
insert into Friendship values (5,6,1)
insert into Friendship values (6,5,1)
insert into Friendship values (7,9,0)
insert into Friendship values (8,10,0)
/*
select u.UserID, u.UserFirstName+' '+u.UserLastName as UserFullName, f.FriendWithID, uf.UserFirstName+' '+uf.UserLastName as FriendFullName,
	   f.IsAccepted
from [User] u join Friendship f on u.UserID=f.UserID
			  join [User] uf on uf.UserID=f.FriendWithID
order by u.UserID
*/

-- insert groups
insert into [Group] values ('Lazy Students', 1)
insert into [Group] values ('Nerds', 2)
insert into [Group] values ('Lazy Nerds', 3)
insert into [Group] values ('Carton-Box Rent in Tel-Aviv', 10)
insert into [Group] values ('Fans of Any Shit', 4)
/*
select g.GroupID, g.GroupName, u.UserFirstName+' '+u.UserLastName as Manager
from [Group] g join [User] u on g.ManagerID=u.UserID
*/

-- insert Group-Members
insert into GroupMembers values (1,2)
insert into GroupMembers values (1,3)
insert into GroupMembers values (1,4)
insert into GroupMembers values (1,5)
insert into GroupMembers values (2,6)
insert into GroupMembers values (2,7)
insert into GroupMembers values (2,8)
insert into GroupMembers values (2,9)
insert into GroupMembers values (2,10)
insert into GroupMembers values (3,1)
insert into GroupMembers values (3,2)
insert into GroupMembers values (3,4)
insert into GroupMembers values (4,6)
insert into GroupMembers values (4,8)
insert into GroupMembers values (4,9)
insert into GroupMembers values (4,10)
insert into GroupMembers values (5,2)
insert into GroupMembers values (5,3)
insert into GroupMembers values (5,4)
insert into GroupMembers values (5,5)
insert into GroupMembers values (1,6)
insert into GroupMembers values (1,7)
insert into GroupMembers values (1,9)
insert into GroupMembers values (2,1)
insert into GroupMembers values (2,3)
insert into GroupMembers values (2,4)
insert into GroupMembers values (2,5)
insert into GroupMembers values (3,6)
insert into GroupMembers values (3,7)
insert into GroupMembers values (3,8)
insert into GroupMembers values (3,9)
insert into GroupMembers values (3,10)
/*
select g.GroupName, u.UserFirstName+' '+u.UserLastName as UserFullName
from [Group] g join GroupMembers gm on g.GroupID=gm.GroupID
			   join [User] u on gm.UserID=u.UserID
order by g.GroupName, u.UserID
*/

-- insert messages
insert into [Message](SenderID, Content, MessageDate) values (1,'hi','2000-01-01 06:30:00')
insert into MessageReceivers values (1,2,1)
insert into MessageReceivers values (1,5,1)
insert into MessageReceivers values (1,7,1)
insert into MessageReceivers values (1,8,1)
insert into MessageReceivers values (1,9,1)
insert into [Message](SenderID, Content, MessageDate) values (2,'hi','2000-01-02 20:00:00')
insert into MessageReceivers values (2,1,1)
insert into [Message](SenderID, Content, MessageDate) values (1,'booo','2000-01-02 20:01:00')
insert into MessageReceivers values (3,2,1)
insert into MessageReceivers values (3,9,1)
insert into [Message](SenderID, Content, MessageDate) values (2,'???','2000-01-02 20:02:00')
insert into MessageReceivers values (4,1,1)
insert into MessageReceivers values (4,3,1)
insert into [Message](SenderID, Content, MessageDate) values (3,'blablabla','2005-05-21 03:00:00')
insert into MessageReceivers values (5,2,1)
insert into MessageReceivers values (5,5,1)
insert into MessageReceivers values (5,8,1)
insert into MessageReceivers values (5,9,1)
insert into [Message](SenderID, Content, MessageDate) values (9,'yustas-aleksu...','2008-03-15 23:30:00')
insert into MessageReceivers values (6,10,1)
insert into [Message](SenderID, Content, MessageDate) values (10,'aleks-yustasu','2008-03-15 23:59:30')
insert into MessageReceivers values (7,9,1)
insert into [Message](SenderID, Content, MessageDate) values (1,'!!!','2012-01-01 00:30:00')
insert into MessageReceivers values (8,7,1)
insert into MessageReceivers values (8,8,1)
insert into MessageReceivers values (8,9,1)
insert into [Message](SenderID, Content, MessageDate) values (4,'!!!!!!!111','2013-01-01 06:30:00')
insert into MessageReceivers values (9,2,1)
insert into MessageReceivers values (9,5,1)
insert into MessageReceivers values (9,6,1)
insert into MessageReceivers values (9,8,1)
insert into MessageReceivers values (9,9,1)
insert into MessageReceivers values (9,10,1)
insert into [Message](SenderID, Content, MessageDate) values (5,'hi','2013-02-01 09:30:00')
insert into MessageReceivers values (10,2,1)
insert into MessageReceivers values (10,4,1)
insert into [Message](SenderID, Content, MessageDate) values (1,'heeey','2013-10-09 12:40:00')
insert into MessageReceivers values (11,7,1)
insert into [Message](SenderID, Content, MessageDate) values (4,')))','2013-12-01 12:30:00')
insert into MessageReceivers values (11,5,1)
insert into [Message](SenderID, Content, MessageDate) values (4,')))))','2013-12-01 13:30:00')
insert into MessageReceivers values (12,5,1)
insert into [Message](SenderID, Content, MessageDate) values (4,'?','2013-12-01 12:30:00')
insert into MessageReceivers values (13,5,1)


/*
select m.MessageID, m.SenderID, us.UserFirstName+' '+us.UserLastName as Sender, mr.UserID as ReceiverID,
	   ur.UserFirstName+' '+ur.UserLastName as Receiver, m.MessageDate, m.[Subject], m.Content
from [User] us join [Message] m on us.UserID=m.SenderID
			   join MessageReceivers mr on m.MessageID=mr.MessageID
			   join [User] ur on mr.UserID=ur.UserID
order by ur.UserID, us.UserID, m.MessageDate
*/

-- insert posts, albums and photos
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (1,'2000-03-07','blablabla',1)
insert into Post(LoadedByUserID,PostDate) values (1,'2001-08-10')
insert into Album values (2,1,'Me','This is my photos')
insert into Post(LoadedByUserID,PostDate) values (1,'2001-08-10')
insert into Pictures values (3,'images/111.jpg',2)
insert into Post(LoadedByUserID,PostDate) values (1,'2001-08-10')
insert into Pictures values (4,'images/222.jpg',2)
insert into Post(LoadedByUserID,PostDate, TextContent) values (1,'2003-08-10','me with my friends')
insert into Pictures values (5,'images/333.jpg',2)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (2,'2003-01-27','abcdefg',2)
insert into Post(LoadedByUserID,PostDate) values (2,'2004-07-10')
insert into Album values (7,2,'Everything','Just photos...')
insert into Post(LoadedByUserID,PostDate) values (2,'2004-07-10')
insert into Pictures values (8,'images/444.jpg',7)
insert into Post(LoadedByUserID,PostDate) values (2,'2004-12-28')
insert into Pictures values (9,'images/555.jpg',7)
insert into Post(LoadedByUserID,PostDate) values (2,'2005-2-15')
insert into Pictures values (10,'images/666.jpg',7)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (3,'2006-04-13','!!!!!!!!!!!11111111',3)
insert into Post(LoadedByUserID,PostDate) values (3,'2007-05-15')
insert into Album values (12,3,'BLAAAAAA','blabla')
insert into Post(LoadedByUserID,PostDate) values (3,'2007-05-15')
insert into Pictures values (13,'images/777.jpg',12)
insert into Post(LoadedByUserID,PostDate) values (3,'2008-11-01')
insert into Pictures values (14,'images/888.jpg',12)
insert into Post(LoadedByUserID,PostDate) values (3,'2008-11-01')
insert into Pictures values (15,'images/999.jpg',12)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (4,'2009-04-08','hellow word',4)
insert into Post(LoadedByUserID,PostDate) values (4,'2009-10-15')
insert into Album values (17,4,'My album','My pictures')
insert into Post(LoadedByUserID,PostDate) values (4,'2009-10-15')
insert into Pictures values (18,'images/1111.jpg',17)
insert into Post(LoadedByUserID,PostDate) values (4,'2009-10-15')
insert into Pictures values (19,'images/2222.jpg',17)
insert into Post(LoadedByUserID,PostDate) values (4,'2009-10-15')
insert into Pictures values (20,'images/3333.jpg',17)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (5,'2009-11-05','blablabla',5)
insert into Post(LoadedByUserID,PostDate) values (5,'2009-11-15')
insert into Album values (22,5,'Without Title','Text-text-text')
insert into Post(LoadedByUserID,PostDate) values (5,'2009-11-15')
insert into Pictures values (23,'images/4444.jpg',22)
insert into Post(LoadedByUserID,PostDate) values (5,'2009-11-15')
insert into Pictures values (24,'images/5555.jpg',22)
insert into Post(LoadedByUserID,PostDate) values (5,'2009-11-15')
insert into Pictures values (25,'images/6666.jpg',22)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (6,'2009-11-05','I cant longer write this!!!!',1)
insert into Post(LoadedByUserID,PostDate) values (6,'2009-11-15')
insert into Album values (27,6,'B&W','Old photos')
insert into Post(LoadedByUserID,PostDate) values (6,'2009-11-15')
insert into Pictures values (28,'images/7777.jpg',27)
insert into Post(LoadedByUserID,PostDate) values (6,'2009-11-15')
insert into Pictures values (29,'images/8888.jpg',27)
insert into Post(LoadedByUserID,PostDate) values (6,'2009-11-15')
insert into Pictures values (30,'images/9999.jpg',27)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (7,'2010-07-25','OMG....(((',2)
insert into Post(LoadedByUserID,PostDate) values (7,'2010-08-15')
insert into Album values (32,7,'Uploaded','Some photos...')
insert into Post(LoadedByUserID,PostDate) values (7,'2011-03-05')
insert into Pictures values (33,'images/11111.jpg',32)
insert into Post(LoadedByUserID,PostDate) values (7,'2012-12-30')
insert into Pictures values (34,'images/22222.jpg',32)
insert into Post(LoadedByUserID,PostDate) values (7,'2013-01-01')
insert into Pictures values (35,'images/33333.jpg',32)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (8,'2014-09-01','Tralala-la-la',3)
insert into Post(LoadedByUserID,PostDate) values (8,'2014-10-03')
insert into Album values (37,8,'Albuuuuuum','Photooooooooooos')
insert into Post(LoadedByUserID,PostDate) values (8,'2014-10-03')
insert into Pictures values (38,'images/44444.jpg',37)
insert into Post(LoadedByUserID,PostDate) values (8,'2014-10-03')
insert into Pictures values (39,'images/55555.jpg',37)
insert into Post(LoadedByUserID,PostDate) values (8,'2014-10-03')
insert into Pictures values (40,'images/66666.jpg',37)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (9,'2014-11-01','Tralala-la-la',3)
insert into Post(LoadedByUserID,PostDate) values (9,'2014-11-10')
insert into Album values (42,9,'Vacation','look and envy!')
insert into Post(LoadedByUserID,PostDate) values (9,'2014-11-10')
insert into Pictures values (43,'images/77777.jpg',42)
insert into Post(LoadedByUserID,PostDate) values (9,'2014-11-11')
insert into Pictures values (44,'images/88888.jpg',42)
insert into Post(LoadedByUserID,PostDate) values (9,'2014-11-11')
insert into Pictures values (45,'images/99999.jpg',42)
insert into Post(LoadedByUserID,PostDate,TextContent,SharedWithGroupID) values (10,'2015-03-01','Hhhhhhhhhhhhhhh!',4)
insert into Post(LoadedByUserID,PostDate) values (10,'2016-08-10')
insert into Album values (47,10,'Pic','...')
insert into Post(LoadedByUserID,PostDate) values (10,'2016-08-10')
insert into Pictures values (48,'images/1.jpg',47)
insert into Post(LoadedByUserID,PostDate) values (10,'2017-10-15')
insert into Pictures values (49,'images/2.jpg',47)
insert into Post(LoadedByUserID,PostDate) values (10,'2018-09-05')
insert into Pictures values (50,'images/3.jpg',47)
/*
select pst.PostID, pst.LoadedByUserID, u.UserFirstName+' '+u.UserLastName as UserFullName, pst.PostDate, pst.SharedWithGroupID, g.GroupName, pst.TextContent,
	   a.PostAlbumID, a.AlbumName, a.[Description], a.OwnerID,
	   p.PostPicturesID, p.BelongsToAlbumID, p.SourceLink
from Post pst left join Album a on pst.PostID=a.PostAlbumID
			  left join Pictures p on pst.PostID=p.PostPicturesID
			  left join [User] u on pst.LoadedByUserID=u.UserID
			  left join [Group] g on pst.SharedWithGroupID=g.GroupID
*/

--insert likes
insert into PostLikes values (1,1,1)
insert into PostLikes values (1,2,1)
insert into PostLikes values (1,3,1)
insert into PostLikes values (1,4,1)
insert into PostLikes values (1,5,1)
insert into PostLikes values (1,6,1)
insert into PostLikes values (1,7,1)
insert into PostLikes values (1,8,1)
insert into PostLikes values (1,9,1)
insert into PostLikes values (2,1,1)
insert into PostLikes values (2,2,1)
insert into PostLikes values (2,3,1)
insert into PostLikes values (2,7,1)
insert into PostLikes values (2,4,1)
insert into PostLikes values (2,5,1)
insert into PostLikes values (2,6,1)
insert into PostLikes values (2,8,1)
insert into PostLikes values (2,9,1)
insert into PostLikes values (2,10,1)
insert into PostLikes values (3,1,1)
insert into PostLikes values (3,2,1)
insert into PostLikes values (3,3,1)
insert into PostLikes values (3,4,1)
insert into PostLikes values (3,5,1)
insert into PostLikes values (3,6,1)
insert into PostLikes values (3,7,1)
insert into PostLikes values (3,9,1)
insert into PostLikes values (3,10,1)
insert into PostLikes values (4,1,1)
insert into PostLikes values (4,2,1)
insert into PostLikes values (4,3,1)
insert into PostLikes values (4,4,1)
insert into PostLikes values (4,5,1)
insert into PostLikes values (4,8,1)
insert into PostLikes values (4,9,1)
insert into PostLikes values (4,10,1)
insert into PostLikes values (5,1,1)
insert into PostLikes values (5,2,1)
insert into PostLikes values (5,3,1)
insert into PostLikes values (5,4,1)
insert into PostLikes values (5,6,1)
insert into PostLikes values (5,7,1)
insert into PostLikes values (5,8,1)
insert into PostLikes values (5,9,1)
insert into PostLikes values (5,10,1)
insert into PostLikes values (6,1,1)
insert into PostLikes values (6,3,1)
insert into PostLikes values (6,4,1)
insert into PostLikes values (6,5,1)
insert into PostLikes values (6,7,1)
insert into PostLikes values (6,8,1)
insert into PostLikes values (6,10,1)
insert into PostLikes values (7,1,1)
insert into PostLikes values (7,2,1)
insert into PostLikes values (7,3,1)
insert into PostLikes values (7,4,1)
insert into PostLikes values (7,5,1)
insert into PostLikes values (7,8,1)
insert into PostLikes values (7,9,1)
insert into PostLikes values (7,10,1)
insert into PostLikes values (8,1,1)
insert into PostLikes values (8,2,1)
insert into PostLikes values (8,3,1)
insert into PostLikes values (8,4,1)
insert into PostLikes values (8,5,1)
insert into PostLikes values (8,7,1)
insert into PostLikes values (8,8,1)
insert into PostLikes values (9,1,1)
insert into PostLikes values (9,5,1)
insert into PostLikes values (9,6,1)
insert into PostLikes values (9,7,1)
insert into PostLikes values (9,8,1)
insert into PostLikes values (9,10,1)
insert into PostLikes values (10,1,1)
insert into PostLikes values (10,3,1)
insert into PostLikes values (10,4,1)
insert into PostLikes values (10,5,1)
insert into PostLikes values (10,6,1)
insert into PostLikes values (10,7,1)
insert into PostLikes values (10,8,1)
insert into PostLikes values (10,9,1)
insert into PostLikes values (10,10,1)
insert into PostLikes values (11,1,1)
insert into PostLikes values (11,2,1)
insert into PostLikes values (11,3,1)
insert into PostLikes values (11,4,1)
insert into PostLikes values (11,5,1)
insert into PostLikes values (11,6,1)
insert into PostLikes values (11,7,1)
insert into PostLikes values (11,9,1)
insert into PostLikes values (11,10,1)
insert into PostLikes values (12,1,1)
insert into PostLikes values (12,2,1)
insert into PostLikes values (12,3,1)
insert into PostLikes values (12,4,1)
insert into PostLikes values (12,5,1)
insert into PostLikes values (12,6,1)
insert into PostLikes values (12,8,1)
insert into PostLikes values (12,9,1)
insert into PostLikes values (12,10,1)
insert into PostLikes values (13,1,1)
insert into PostLikes values (13,2,1)
insert into PostLikes values (13,3,1)
insert into PostLikes values (13,5,1)
insert into PostLikes values (13,6,1)
insert into PostLikes values (13,7,1)
insert into PostLikes values (13,8,1)
insert into PostLikes values (13,9,1)
insert into PostLikes values (13,10,1)
insert into PostLikes values (14,1,1)
insert into PostLikes values (14,2,1)
insert into PostLikes values (14,3,1)
insert into PostLikes values (14,4,1)
insert into PostLikes values (14,5,1)
insert into PostLikes values (14,8,1)
insert into PostLikes values (14,9,1)
insert into PostLikes values (15,2,1)
insert into PostLikes values (15,4,1)
insert into PostLikes values (15,5,1)
insert into PostLikes values (15,6,1)
insert into PostLikes values (15,7,1)
insert into PostLikes values (15,8,1)
insert into PostLikes values (16,1,1)
insert into PostLikes values (16,3,1)
insert into PostLikes values (16,4,1)
insert into PostLikes values (16,5,1)
insert into PostLikes values (16,6,1)
insert into PostLikes values (16,9,1)
insert into PostLikes values (16,10,1)
insert into PostLikes values (17,1,1)
insert into PostLikes values (17,4,1)
insert into PostLikes values (17,5,1)
insert into PostLikes values (17,6,1)
insert into PostLikes values (17,8,1)
insert into PostLikes values (17,9,1)
insert into PostLikes values (17,10,1)
insert into PostLikes values (18,1,1)
insert into PostLikes values (18,3,1)
insert into PostLikes values (18,4,1)
insert into PostLikes values (18,5,1)
insert into PostLikes values (18,6,1)
insert into PostLikes values (18,8,1)
insert into PostLikes values (19,3,1)
insert into PostLikes values (19,4,1)
insert into PostLikes values (19,5,1)
insert into PostLikes values (19,6,1)
insert into PostLikes values (19,7,1)
insert into PostLikes values (19,8,1)
insert into PostLikes values (19,9,1)
insert into PostLikes values (20,3,1)
insert into PostLikes values (20,5,1)
insert into PostLikes values (20,6,1)
insert into PostLikes values (20,7,1)
insert into PostLikes values (20,8,1)
insert into PostLikes values (20,9,1)
insert into PostLikes values (20,10,1)
insert into PostLikes values (21,1,1)
insert into PostLikes values (21,3,1)
insert into PostLikes values (21,4,1)
insert into PostLikes values (21,5,1)
insert into PostLikes values (21,6,1)
insert into PostLikes values (21,9,1)
insert into PostLikes values (22,1,1)
insert into PostLikes values (22,2,1)
insert into PostLikes values (22,4,1)
insert into PostLikes values (22,5,1)
insert into PostLikes values (22,8,1)
insert into PostLikes values (22,9,1)
insert into PostLikes values (22,10,1)
insert into PostLikes values (23,1,1)
insert into PostLikes values (23,3,1)
insert into PostLikes values (23,4,1)
insert into PostLikes values (23,5,1)
insert into PostLikes values (23,6,1)
insert into PostLikes values (23,7,1)
insert into PostLikes values (23,9,1)
insert into PostLikes values (23,10,1)
insert into PostLikes values (24,1,1)
insert into PostLikes values (24,2,1)
insert into PostLikes values (24,3,1)
insert into PostLikes values (24,4,1)
insert into PostLikes values (24,5,1)
insert into PostLikes values (24,7,1)
insert into PostLikes values (24,9,1)
insert into PostLikes values (25,1,1)
insert into PostLikes values (25,2,1)
insert into PostLikes values (25,4,1)
insert into PostLikes values (25,6,1)
insert into PostLikes values (25,7,1)
insert into PostLikes values (25,8,1)
insert into PostLikes values (26,4,1)
insert into PostLikes values (26,6,1)
insert into PostLikes values (26,10,1)
insert into PostLikes values (27,1,1)
insert into PostLikes values (27,2,1)
insert into PostLikes values (27,4,1)
insert into PostLikes values (27,8,1)
insert into PostLikes values (27,9,1)
insert into PostLikes values (28,1,1)
insert into PostLikes values (28,4,1)
insert into PostLikes values (28,6,1)
insert into PostLikes values (28,7,1)
insert into PostLikes values (28,8,1)
insert into PostLikes values (28,10,1)
insert into PostLikes values (29,1,1)
insert into PostLikes values (29,3,1)
insert into PostLikes values (29,4,1)
insert into PostLikes values (29,5,1)
insert into PostLikes values (29,7,1)
insert into PostLikes values (29,8,1)
insert into PostLikes values (29,9,1)
insert into PostLikes values (29,10,1)
insert into PostLikes values (30,2,1)
insert into PostLikes values (30,4,1)
insert into PostLikes values (30,6,1)
insert into PostLikes values (30,8,1)
insert into PostLikes values (30,10,1)
insert into PostLikes values (31,1,1)
insert into PostLikes values (31,3,1)
insert into PostLikes values (31,4,1)
insert into PostLikes values (31,5,1)
insert into PostLikes values (31,6,1)
insert into PostLikes values (31,9,1)
insert into PostLikes values (32,1,1)
insert into PostLikes values (32,2,1)
insert into PostLikes values (32,4,1)
insert into PostLikes values (32,5,1)
insert into PostLikes values (32,8,1)
insert into PostLikes values (32,9,1)
insert into PostLikes values (32,10,1)
insert into PostLikes values (33,1,1)
insert into PostLikes values (33,3,1)
insert into PostLikes values (33,5,1)
insert into PostLikes values (33,6,1)
insert into PostLikes values (33,7,1)
insert into PostLikes values (33,9,1)
insert into PostLikes values (33,10,1)
insert into PostLikes values (34,1,1)
insert into PostLikes values (34,2,1)
insert into PostLikes values (34,3,1)
insert into PostLikes values (34,4,1)
insert into PostLikes values (34,5,1)
insert into PostLikes values (35,1,1)
insert into PostLikes values (35,2,1)
insert into PostLikes values (35,4,1)
insert into PostLikes values (35,6,1)
insert into PostLikes values (35,7,1)
insert into PostLikes values (35,8,1)
insert into PostLikes values (36,1,1)
insert into PostLikes values (36,2,1)
insert into PostLikes values (36,3,1)
insert into PostLikes values (36,4,1)
insert into PostLikes values (36,6,1)
insert into PostLikes values (36,7,1)
insert into PostLikes values (36,10,1)
insert into PostLikes values (37,1,1)
insert into PostLikes values (37,4,1)
insert into PostLikes values (37,8,1)
insert into PostLikes values (37,9,1)
insert into PostLikes values (38,1,1)
insert into PostLikes values (38,4,1)
insert into PostLikes values (38,5,1)
insert into PostLikes values (38,6,1)
insert into PostLikes values (38,8,1)
insert into PostLikes values (39,1,1)
insert into PostLikes values (39,2,1)
insert into PostLikes values (39,9,1)
insert into PostLikes values (39,10,1)
insert into PostLikes values (40,1,1)
insert into PostLikes values (40,4,1)
insert into PostLikes values (40,10,1)
insert into PostLikes values (41,1,1)
insert into PostLikes values (41,3,1)
insert into PostLikes values (41,4,1)
insert into PostLikes values (41,5,1)
insert into PostLikes values (41,6,1)
insert into PostLikes values (41,9,1)
insert into PostLikes values (42,1,1)
insert into PostLikes values (42,2,1)
insert into PostLikes values (42,4,1)
insert into PostLikes values (42,5,1)
insert into PostLikes values (42,8,1)
insert into PostLikes values (42,9,1)
insert into PostLikes values (42,10,1)
insert into PostLikes values (43,1,1)
insert into PostLikes values (43,3,1)
insert into PostLikes values (43,5,1)
insert into PostLikes values (43,6,1)
insert into PostLikes values (43,7,1)
insert into PostLikes values (43,9,1)
insert into PostLikes values (43,10,1)
insert into PostLikes values (44,1,1)
insert into PostLikes values (44,2,1)
insert into PostLikes values (44,3,1)
insert into PostLikes values (44,4,1)
insert into PostLikes values (44,5,1)
insert into PostLikes values (45,1,1)
insert into PostLikes values (45,2,1)
insert into PostLikes values (45,4,1)
insert into PostLikes values (45,6,1)
insert into PostLikes values (45,7,1)
insert into PostLikes values (45,8,1)
insert into PostLikes values (46,1,1)
insert into PostLikes values (46,3,1)
insert into PostLikes values (46,4,1)
insert into PostLikes values (46,7,1)
insert into PostLikes values (46,9,1)
insert into PostLikes values (46,10,1)
insert into PostLikes values (47,1,1)
insert into PostLikes values (47,4,1)
insert into PostLikes values (47,8,1)
insert into PostLikes values (47,9,1)
insert into PostLikes values (48,1,1)
insert into PostLikes values (48,2,1)
insert into PostLikes values (48,4,1)
insert into PostLikes values (48,6,1)
insert into PostLikes values (48,7,1)
insert into PostLikes values (49,1,1)
insert into PostLikes values (49,2,1)
insert into PostLikes values (49,3,1)
insert into PostLikes values (49,4,1)
insert into PostLikes values (50,1,1)
insert into PostLikes values (50,3,1)
insert into PostLikes values (50,4,1)
insert into PostLikes values (50,10,1)
/*
select *
from PostLikes
*/

-- insert profile-photo
update [User] set ProfilePictureID=3 where [UserID]=1
update [User] set ProfilePictureID=8 where [UserID]=2
update [User] set ProfilePictureID=13 where [UserID]=3
update [User] set ProfilePictureID=18 where [UserID]=4
update [User] set ProfilePictureID=23 where [UserID]=5
update [User] set ProfilePictureID=28 where [UserID]=6
update [User] set ProfilePictureID=33 where [UserID]=7
update [User] set ProfilePictureID=38 where [UserID]=8
update [User] set ProfilePictureID=43 where [UserID]=9
update [User] set ProfilePictureID=48 where [UserID]=10
/*
select *
from [User]
*/

-- insert tags
insert into PictureTags values (3,1,1)
insert into PictureTags values (4,2,1)
insert into PictureTags values (4,3,1)
insert into PictureTags values (4,4,1)
insert into PictureTags values (5,6,1)
insert into PictureTags values (5,7,1)
insert into PictureTags values (8,2,1)
insert into PictureTags values (9,1,1)
insert into PictureTags values (9,5,1)
insert into PictureTags values (9,9,1)
insert into PictureTags values (10,1,1)
insert into PictureTags values (10,2,1)
insert into PictureTags values (10,7,1)
insert into PictureTags values (13,3,1)
insert into PictureTags values (14,3,1)
insert into PictureTags values (14,6,1)
insert into PictureTags values (14,8,1)
insert into PictureTags values (15,8,1)
insert into PictureTags values (15,10,1)
insert into PictureTags values (18,4,1)
insert into PictureTags values (19,3,1)
insert into PictureTags values (19,4,1)
insert into PictureTags values (20,6,1)
insert into PictureTags values (20,8,1)
insert into PictureTags values (20,9,1)
insert into PictureTags values (23,5,1)
insert into PictureTags values (24,5,1)
insert into PictureTags values (24,6,1)
insert into PictureTags values (25,7,1)
insert into PictureTags values (25,10,1)
insert into PictureTags values (28,6,1)
insert into PictureTags values (29,6,1)
insert into PictureTags values (29,3,1)
insert into PictureTags values (29,1,1)
insert into PictureTags values (30,7,1)
insert into PictureTags values (30,4,1)
insert into PictureTags values (33,7,1)
insert into PictureTags values (34,7,1)
insert into PictureTags values (34,8,1)
insert into PictureTags values (35,7,1)
insert into PictureTags values (35,10,1)
insert into PictureTags values (38,8,1)
insert into PictureTags values (39,8,1)
insert into PictureTags values (39,3,1)
insert into PictureTags values (40,1,1)
insert into PictureTags values (40,8,1)
insert into PictureTags values (43,9,1)
insert into PictureTags values (44,9,1)
insert into PictureTags values (44,10,1)
insert into PictureTags values (45,4,1)
insert into PictureTags values (45,9,1)
insert into PictureTags values (48,10,1)
insert into PictureTags values (49,10,1)
insert into PictureTags values (49,8,1)
insert into PictureTags values (50,1,1)
insert into PictureTags values (50,3,1)
insert into PictureTags values (50,10,1)
/*
select *
from PictureTags
*/